/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./apps/**/*.{html,js,jsx}",
    "./shared/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#c84a41",
        "primary-fixed": "#d1e4ff",
        "surface-container-low": "#f0f4f8",
        "surface": "#f6fafe",
        "on-secondary-fixed-variant": "#005319",
        "tertiary-fixed": "#ffdad6",
        "on-error": "#ffffff",
        "surface-variant": "#dfe3e7",
        "background": "#f6fafe",
        "primary-container": "#4d77a6",
        "on-surface": "#171c1f",
        "surface-container-high": "#e4e9ed",
        "secondary-fixed": "#9df79f",
        "surface-container-lowest": "#ffffff",
        "outline": "#727780",
        "on-tertiary": "#ffffff",
        "on-background": "#171c1f",
        "on-primary-fixed-variant": "#184975",
        "outline-variant": "#c2c7d0",
        "primary": "#325e8c",
        "on-secondary-container": "#14722b",
        "on-primary-container": "#fdfcff",
        "error-container": "#ffdad6",
        "surface-container-highest": "#dfe3e7",
        "primary-fixed-dim": "#a0cafd",
        "inverse-primary": "#a0cafd",
        "on-secondary": "#ffffff",
        "surface-bright": "#f6fafe",
        "surface-dim": "#d6dade",
        "on-tertiary-fixed": "#410002",
        "secondary-container": "#9af49c",
        "on-error-container": "#93000a",
        "secondary": "#0b6d27",
        "tertiary-fixed-dim": "#ffb4ab",
        "error": "#ba1a1a",
        "inverse-on-surface": "#edf1f5",
        "on-primary-fixed": "#001d36",
        "secondary-fixed-dim": "#81da85",
        "inverse-surface": "#2c3134",
        "surface-tint": "#35618f",
        "on-tertiary-fixed-variant": "#891c19",
        "on-surface-variant": "#42474f",
        "on-secondary-fixed": "#002106",
        "tertiary": "#a7322b",
        "on-tertiary-container": "#fffbff",
        "on-primary": "#ffffff",
        "surface-container": "#eaeef2"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "card-gap": "20px",
        "gutter": "16px",
        "container-padding": "24px",
        "element-tight": "8px",
        "section-margin": "32px"
      },
      fontFamily: {
        "label-md": ["Manrope"],
        "body-lg": ["Manrope"],
        "headline-lg": ["Manrope"],
        "body-md": ["Manrope"],
        "headline-lg-mobile": ["Manrope"],
        "headline-sm": ["Manrope"],
        "headline-md": ["Manrope"],
        "label-sm": ["Manrope"]
      },
      fontSize: {
        "label-md": ["13px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "headline-sm": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
        "headline-md": ["22px", {"lineHeight": "28px", "fontWeight": "600"}],
        "label-sm": ["11px", {"lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
